language: java
addons:
  sonarcloud:
    organization: grigory-rylov-github
    token:
      secure: iP5Peg0Axb4iCZYHBWq3qWYa/0idj2IjtZPYL9aO2npGSyJuTx5/BxQsXPmCItT4VIZcqhWEsqOzX/EjtLgLEiPF51fw5ZLiGrdXmp2nmmslhfQnp+9QXl0/hyyGskfM8fdTOGxbaEZBSycwpTKab5uMHRlK8WoQxp/Rt3UvTagsQTMh0v1NF5cAJiIDcV6CQHEKhbi/Ein/hYhl+2zzpCixQoOrq/IB8KCmSno8NNBHi4KnstCllwss1oTU39v8kXwvLpIieaAmXxdER0ESDhviqI0AE4Qg5+iR4eSQ0bd36pNA7M4ObSEJn1r7rv3VIskcfa+mILKhZpvBjHfnFS/5CWJ/H7ooO5maLWbdnRgYUuvE0RwyDzPBfiVNabjYbGNqxYqjmcTF665Cb0Y1tXQjiZq6vsgU0vuEQgghTuZM9Rkvzrs+6cExgzEVwM6LQPWZmp3ubnYnqgl4tfLRhUGzDG+aNXmToTQB6hXN2LPEqMMnnFtre9tE2gvNpDSe3s+CrfxQglBplcgSHF4yyJI4TGDOdCDBaFxj434XwN7isXFHYnw2urhhF0CdEqyfmTmjhHTke5uaXDGSNBOvrqBdW+bqiEVZCxALAgEkXiSSgJBC/zv9duIQpOfScvMRGQPvgb6lAFMmEMxKU/inQfDtlIc5R3ROcoYHaivNFxc=
    branches:
    - master
    - .*
script:
- ./gradlew sonarqube
after_success:
- mvn clean test jacoco:report coveralls:jacoco
env:
  global:
    secure: D302LkhkpkBadL+QpC5/mzyiIGIeS0uP1reIJV9Li+338Xu2gR6wDj6lG1gq79ceSoMOcPr+2p8nq09nPsqPfpOo9Xrw/ipkMX4AYD/X+j+f2Guke6w8AFRntbNcptviiESouF7c11UEqJ5HDukZkjYnWPz2q+wdy7685li3rDByMjM+R2xkePgsBwZ4s7TMZj+jbTZWSLmXP0KrryM9ZlYJ1eHshiPeDcmKVrS4ZMhtW49mRXYZg+2l533xj7hG2LKMwsSplhe0zR+2ILLbtyJgKuY1UntZZKvg4DlAmPA8+uLxvgRI2IePaOjIYTWrIEoWKewy4W9jhZpDvldRKWT2uR2ilve6PGEzG73Xk/EplDsMTbMOjye4ERD8KGPzF14WVfB96a3pEQ+irh4qjca62KPhVa0gjxnZ7vyPqrlW9KUREKPnM3hTyULF9FP2o3oZY/I+vf5CUTv5nsHyJUJmstGfeJy9NkVCrmlHrPBslGxIPmgfbERJ7L7V46RY47YPpZw/Nm8heJaBLuavBhOUF079vv+7Q6ctdo0IPIBXDxuLkNfb1PVzH0hbaNQMyKTrKnIkxggR0x9UEGKkA3SEKKnONYVJpgeVPZUSimI+DjAmiEdANpaGYzLw4FEONHwMBsq9q9yCMnPtQWugahoaxXDodYIIex15MUQaRn8=
