language: java
addons:
  sonarcloud:
    organization: grigory-rylov-github
    token:
      secure: iP5Peg0Axb4iCZYHBWq3qWYa/0idj2IjtZPYL9aO2npGSyJuTx5/BxQsXPmCItT4VIZcqhWEsqOzX/EjtLgLEiPF51fw5ZLiGrdXmp2nmmslhfQnp+9QXl0/hyyGskfM8fdTOGxbaEZBSycwpTKab5uMHRlK8WoQxp/Rt3UvTagsQTMh0v1NF5cAJiIDcV6CQHEKhbi/Ein/hYhl+2zzpCixQoOrq/IB8KCmSno8NNBHi4KnstCllwss1oTU39v8kXwvLpIieaAmXxdER0ESDhviqI0AE4Qg5+iR4eSQ0bd36pNA7M4ObSEJn1r7rv3VIskcfa+mILKhZpvBjHfnFS/5CWJ/H7ooO5maLWbdnRgYUuvE0RwyDzPBfiVNabjYbGNqxYqjmcTF665Cb0Y1tXQjiZq6vsgU0vuEQgghTuZM9Rkvzrs+6cExgzEVwM6LQPWZmp3ubnYnqgl4tfLRhUGzDG+aNXmToTQB6hXN2LPEqMMnnFtre9tE2gvNpDSe3s+CrfxQglBplcgSHF4yyJI4TGDOdCDBaFxj434XwN7isXFHYnw2urhhF0CdEqyfmTmjhHTke5uaXDGSNBOvrqBdW+bqiEVZCxALAgEkXiSSgJBC/zv9duIQpOfScvMRGQPvgb6lAFMmEMxKU/inQfDtlIc5R3ROcoYHaivNFxc=
    branches:
    - master
    - .*
script:
- ./gradlew sonarqube
after_success:
- mvn clean test jacoco:report coveralls:jacoco
env:
  global:
    secure: I8A6vA34vOtEcwtd4d38VHGLhYmclneYUxHLNMxi+8pt60IOPzTMMyoe5htjPvUJFzSZ4yZrialrqlFWsXiQT7HA8LpW1cx7tJlAqIm74OtmJI3Ha2hm6U2/3JZFj207aaC/s88I5umZQWcdGIM4FfOADpmdJlFn0Wy64lztH+kUi4Gr6XnLySv9bVGOPAXi9q202yMAyAaDDspWxlxo/i0UH2PQDXN3YaOPent9AlV9hHMixXdRSZbLewIiquHSqfPB72M7j/QiuulbxK9PfGZdt8cc6FIcQ8TfCP7VQUOysptLrhRfB23CSBzRhbZDqg6oJuKsiL2JYPtR3ZafqCP2NH2L4LRwmTvI7r7V4/UWmDl1+dqT4CkSk2oNEY4UML4/Oe1ciskRtu+ujO4AVTX3cGjHuhfsKFF72qJBVwd7rJrFtX6gfb3eA6tYgOVcs1JSthcjzh/Je5uJkc6WMNDARNZjt+lNTq0gRGdMZnp5daqfk70UDHXaxhgVEdfBTVJKIreD90xxpYddM3XMPRZR9nonv50bgcp0qe6tdyalb15HilhR0lkTiSdQwxStFadkWYJHXcQt/C9bml563yUBUwcxIGOcgEMTlbjX8kk4/BASviBfCWGs2ZzylmEu8yQltDyC/sPG1saCTIy83uXLuYzd0KGEUvCrhDBmHyQ=
